---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: "ansible-role-repository_caddy"

  post_tasks:
    - name: Install caddy for testing the repository works
      ansible.builtin.package:
        name: "caddy"
        state: present
