---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    verify:
      package: "caddy"


  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check if package is installed
      ansible.builtin.package:
        name: "{{ verify.package }}"
        state: present
      check_mode: true
      register: package_installed
      failed_when: (package_installed is changed) or (package_installed is failed)
